nelmio_api_doc:
    documentation:
        info:
            title: Admin Service
            description: Application API
            version: 1.0.0
        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: UUID
    areas: # to filter documented areas
        path_patterns:
            - ^/auth
            - ^/files
            - ^/health
            - ^/ready
            - ^/users
            - ^/oil-service
            - ^/warehouse
            - ^/chat
