version: v1
# If advanced mode is active CI pipelines use Dockerfile and helm descriptor from repository
advancedMode:
  enabled: true
build:
  # recommendation: use the official composer repo if you want to change runtime version: https://hub.docker.com/_/composer
  image: miki1/php-nginx-8.3-rdkafka:v0.3.0
  # definitions of environment variables that will be used in all stages of your pipeline
  environmentVariables: []
  #- key: variable1
  #  value: value1
  #- key: variable2
  #  value: value2
  #- key: variable3
  #  value: value3
  pipelines:
    release:
      pipeline: php8.3-composer-app-release-analysis
    preview:
      pipeline: php8.3-composer-app-preview-analysis
    triggers: []
runtime:
  # Image is used as a base image for your runtime container
  image: webdevops/php-nginx:8.3-alpine
  # Port on which the service will be exposed
  port: "80"
  endpoints:
    external:
      # Expose service to external endpoint
      enabled: true